// Generated by CoffeeScript 1.9.3
(function() {
  var app;

  app = angular.module('sa');

  app.controller('patient_create', [
    '$scope', 'storage', '$state', function($scope, storage, $state) {
      $scope.mode = 'create';
      return $scope.submit = function() {
        if ($scope.patientForm.$invalid) {
          return;
        }
        $scope.patient.id = ++storage.usersCount;
        storage.users.push($scope.patient);
        return $state.go('patient_list');
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=create.js.map
