// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('sa');

  app.controller('patient_edit', [
    '$scope', 'storage', function($scope, storage) {
      return $scope.mode = 'edit';
    }
  ]);

}).call(this);

//# sourceMappingURL=edit.js.map
