// Generated by CoffeeScript 1.9.3
(function() {
  var app;

  app = angular.module('sa');

  app.controller('patient_list', [
    '$scope', 'storage', function($scope, storage) {
      $scope.users = storage.users;
      $scope.deletePatient = function(id) {
        var found, i, j, k, len, ref;
        ref = $scope.users;
        for (k = j = 0, len = ref.length; j < len; k = ++j) {
          i = ref[k];
          if (i.id === id) {
            found = true;
          }
          if (found) {
            $scope.users[k] = $scope.users[k + 1];
          }
        }
        return $scope.users.pop();
      };
      $scope.sort = null;
      return $scope.setSort = function(f) {
        if ($scope.sort === f) {
          return $scope.sort = '-' + f;
        } else {
          return $scope.sort = f;
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=list.js.map
