// Generated by CoffeeScript 1.9.3
(function() {
  var app;

  app = angular.module('sa');

  app.factory('storage', function() {
    if (this.users == null) {
      this.users = [];
    }
    if (this.usersCount == null) {
      this.usersCount = 0;
    }
    return this;
  });

}).call(this);

//# sourceMappingURL=services.js.map
